language: node_js
node_js:
  - "stable"
#sudo: false
cache:
  directories:
    - node_modules
script:
#  - npm run build
   - echo "npm test temporarily disabled"
deploy:
  provider: heroku
  api_key:
    secure: 8488c898-cdf7-4ada-8f56-9a58631293e7
  app: binluis-parkingwebapp
  on:
    repo: BinLuIS/ParkingWebApp
#notifications:
#  webhooks:
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
